//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality
    {
        public int QualitiesID { get; set; }
        public string Quality1 { get; set; }
    }
}
